### ISSUE TITLE
Is this still working

### ISSUE THREAD

**Issue by jussbba** [GregoryDosh/Home-Assistant-TwitchCast-Service#1]
Hello,

Is this still working. I am looking for a way to cast twitch streams to chromecast. 

I used media extractro component before but it doesn't work anymore.

Thanks.

**Comment by GregoryDosh** [comment]
@jussbba This actually broke some time back and I had updated it locally but forgot to push some of those changes to this repo. I'll do that here in just a little bit.

**Comment by GregoryDosh** [comment]
I've been using it like this.

# Package Yaml
```yaml
twitchcast:
  chromecast_host: 192.168.1.25
  chromecast_name: Living Room TV
  layout: right

script:
  launch_twitchcast:
    alias: Launch TwitchCast
    sequence:
      - service: remote.turn_on
        data:
          entity_id: remote.living_room_tv
          activity: "Chromecast"
      - delay: 00:00:01
      - service: twitchcast.cast_stream
        data_template:
          channel: "{{ states('input_text.tc_channel') }}"
          layout: "{{ states('input_select.tc_layout') }}"

input_text:
  tc_channel:
    name: TwitchCast Channel
    initial: ""
    icon: mdi:account

input_select:
  tc_layout:
    name: TwitchCast Layout
    options:
     - right
     - left
     - top
     - bottom
    initial: right
    icon: mdi:page-layout-body
```

# Lovelace UI
```yaml
cards:
  - card:
      title: Twitchcast
      type: entities
    entities:
      - entity: input_text.tc_channel
        icon: 'mdi:account'
        name: Channel
    filter:
      include:
        - options:
            secondary_info: >
              <b style="color: var(--primary-color)">[[ {entity}.attributes.game
              ]]</b> - [[ {entity}.attributes.title ]]
            type: 'custom:secondaryinfo-entity-row'
          sort:
            method: last_changed
          state: streaming
    sort:
      method: domain
      reverse: true
    type: 'custom:auto-entities'
  - cards:
      - entity: input_select.tc_layout
        icon: 'mdi:chevron-up'
        name: Top
        tap_action:
          action: call-service
          service: input_select.select_option
          service_data:
            entity_id: input_select.tc_layout
            option: top
        type: entity-button
      - entity: input_select.tc_layout
        icon: 'mdi:chevron-left'
        name: Left
        tap_action:
          action: call-service
          service: input_select.select_option
          service_data:
            entity_id: input_select.tc_layout
            option: left
        type: entity-button
      - entity: input_select.tc_layout
        icon: 'mdi:chevron-right'
        name: Right
        tap_action:
          action: call-service
          service: input_select.select_option
          service_data:
            entity_id: input_select.tc_layout
            option: right
        type: entity-button
      - entity: input_select.tc_layout
        icon: 'mdi:chevron-down'
        name: Bottom
        tap_action:
          action: call-service
          service: input_select.select_option
          service_data:
            entity_id: input_select.tc_layout
            option: bottom
        type: entity-button
      - entity: script.launch_twitchcast
        icon: 'mdi:rocket'
        name: Launch
        tap_action:
          action: call-service
          service: script.launch_twitchcast
        type: entity-button
    type: horizontal-stack
  - cards:
      - content: '&nbsp;&nbsp;<ha-icon icon="mdi:television"></ha-icon>'
        type: markdown
      - entity: script.harmony_tv_off
        name: 'Off'
        tap_action:
          action: toggle
        type: entity-button
      - entity: script.harmony_tv_on
        name: 'On'
        tap_action:
          action: toggle
        type: entity-button
      - entity: script.harmony_tv_vol_mute
        name: Mute
        tap_action:
          action: toggle
        type: entity-button
      - entity: script.harmony_tv_vol_down
        name: Vol -
        tap_action:
          action: toggle
        type: entity-button
      - entity: script.harmony_tv_vol_up
        name: Vol +
        tap_action:
          action: toggle
        type: entity-button
    type: horizontal-stack
type: vertical-stack

```
